#!/usr/bin/env bash

echo 'running pre-commit hook!'
echo 'this hook will:'
echo '  1 - run lint check (`npm run lint:check`)'
echo '  2 - run format check (`npm run format:check`)'
echo '  3 - run OpenAPI spec generation which stores the spec in docs/openapi.yaml (`npm run docs:openapi:generate`)'
echo '  4 - run all tests and store the output without time durations in logs/test.log (`npm run test:all:log`)'
echo '  5 - add docs/openapi.yaml and logs/test.log to the commit (CI pipiline fails if you push a commit with outdated docs/openapi.yaml or logs/test.log)'
echo 'if you do not want to run all of this, run git commit with --no-verify'

npm run lint:check
if [ $? -ne 0 ]; then
  echo 'lint check failed, please fix the errors before committing'
  exit 1
fi

npm run format:check
if [ $? -ne 0 ]; then
  echo 'format check failed, please fix the errors before committing'
  exit 1
fi

npm run docs:openapi:generate
if [ $? -ne 0 ]; then
  echo 'OpenAPI spec generation failed, please fix the errors before committing'
  exit 1
fi

npm run test:all:log
if [ $? -ne 0 ]; then
  echo 'tests failed, please fix the errors before committing'
  exit 1
fi

git add docs/openapi.yaml logs/test.log
if [ $? -ne 0 ]; then
  echo 'failed to add docs/openapi.yaml and logs/test.log to the commit, please fix the errors before committing'
  exit 1
fi
